name: Aggiornamento Dati TT

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  aggiorna-dati:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - run: pip install cloudscraper
      
      - run: python scraper_tt.py
      
      - run: git config --global user.name "Bot" && git config --global user.email "bot@github.com" && git add database_h2h.json && git commit -m "Aggiornamento" || echo "Nessuna modifica" && git push origin main
