name: aggiorna-dati

on:
  workflow_dispatch: 
  schedule:
    - cron: '*/15 * * * *'

jobs:
  aggiornamento:
    runs-on: ubuntu-latest
    # Queste sono le autorizzazioni che permettono al bot di scrivere sul repository
    permissions:
      contents: write

    steps:
      - name: Clona il repository
        uses: actions/checkout@v3

      - name: Installa Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installa librerie
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Esegui lo Scraper
        run: python scraper_tt.py

      - name: Salva i nuovi dati
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add database_h2h.json
          git commit -m "Aggiornamento dati API" || echo "Nessun nuovo dato da salvare"
          git push
